name: enough_mail
description: IMAP and SMTP clients in pure Dart. Strives to be compliant with IMAP4 rev1, IMAP IDLE, IMAP METADATA Extension and SMTP.
version: 0.0.8
homepage: https://github.com/Enough-Software/enough_mail

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  event_bus: ^1.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
