name: enough_mail
description: IMAP, POP3 and SMTP in pure Dart. Choose between a low level and a high level API for mailing. Parse and generate MIME messages. Discover email settings.
version: 1.0.0
homepage: https://github.com/Enough-Software/enough_mail

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pedantic: ^1.11.0
  event_bus: ^2.0.0
  crypto: ^3.0.0
  encrypt: ^5.0.0-beta.1
  pointycastle: ^3.0.0-nullsafety.2
  basic_utils: ^3.0.0-nullsafety.0
  xml: ^5.0.2
  intl: ^0.17.0
  enough_serialization: ^1.3.0
    #path: ../enough_serialization
  enough_convert: ^1.2.0
    # path: ../enough_convert
  collection: ^1.15.0



dev_dependencies:
  test: ^1.16.7
