name: enough_mail
description: IMAP, POP3 and SMTP clients in pure Dart. Provides low level support for these mail protocols.
version: 0.0.27
homepage: https://github.com/Enough-Software/enough_mail

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  event_bus: ^1.1.1
  intl: ^0.16.1
  crypto: ^2.1.4
  basic_utils: ^2.5.3
  xml: ^3.6.1


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
