name: enough_mail
description: IMAP and SMTP clients in pure Dart. Strives to be compliant with IMAP4 rev1, IMAP IDLE, IMAP METADATA Extension and SMTP.
version: 0.0.13
homepage: https://github.com/Enough-Software/enough_mail

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  event_bus: ^1.1.1
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
