name: enough_mail
description: IMAP, POP3 and SMTP email clients in pure Dart. Choose between a low level and a high level API for mailing. Parse and generate MIME messages.
version: 0.3.0
homepage: https://github.com/Enough-Software/enough_mail

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pedantic: ^1.9.2
  event_bus: '>=1.1.1 <3.0.0'
  crypto: '>=2.0.0 <4.0.0'
  basic_utils: '>=1.7.0 <4.0.0'
  xml: '>=4.0.0 <6.0.0'
  intl: '>= 0.15.0 <2.0.0'
  encrypt: '>=4.0.0 <6.0.0'
  enough_serialization: ^1.3.0
    #path: ../enough_serialization
  enough_convert: ^1.1.0
    # path: ../enough_convert



dev_dependencies:
  test: ^1.15.4
